export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const UPDATE_EMAIL = "UPDATE_EMAIL";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_ROLE = "UPDATE_ROLE";
export const UPDATE_MENTOR_DATA = "UPDATE_MENTOR_DATA";
export const UPDATE_STARTUP_DATA = "UPDATE_STARTUP_DATA";
